apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: cng7hobb6-nodejs 
  janus-idp.io/tekton: cng7hobb6-nodejs
  backstage.io/kubernetes-id: cng7hobb6-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cng7hobb6-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  